# Generated by Django 3.1.4 on 2020-12-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('co_type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sales_vol', models.BigIntegerField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('repertory', models.BigIntegerField(max_length=50)),
                ('des', models.CharField(max_length=500)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.comment')),
            ],
        ),
    ]
