# Generated by Django 3.1.4 on 2020-12-24 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='repertory',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_vol',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 19, 41, 56, 742304)),
        ),
    ]
