# Generated by Django 3.1.4 on 2020-12-30 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201224_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 18, 48, 33, 559262)),
        ),
        migrations.AlterField(
            model_name='product',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.comment'),
        ),
    ]
